# Generated by Django 3.1.5 on 2021-01-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemimage',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
